const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs'),os=require('node:os'),path=require('node:path');const {LoginMemory,validAccount}=require('../dist/login-memory');const {managedConfigs}=require('../dist/login');
function fixture(run){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'qq-memory-test-'));try{run(dir)}finally{fs.rmSync(dir,{recursive:true,force:true})}}
test('remembered account persists across application restart; no password stored',()=>fixture(dir=>{const a=new LoginMemory(dir);assert.equal(a.remember,true);assert.equal(a.account,'');a.record('123456');const b=new LoginMemory(dir);assert.equal(b.account,'123456');assert.deepEqual(JSON.parse(fs.readFileSync(path.join(dir,'login-memory.json'))),{remember:true,account:'123456'})}));
test('disabled remembering clears account and prevents recording future logins',()=>fixture(dir=>{const a=new LoginMemory(dir);a.record('123456');a.setRemember(false);a.record('654321');const b=new LoginMemory(dir);assert.equal(b.remember,false);assert.equal(b.account,'');b.setRemember(true);b.record('654321');assert.equal(new LoginMemory(dir).account,'654321')}));
test('switch account forgets selected account without deleting runtime data',()=>fixture(dir=>{fs.writeFileSync(path.join(dir,'runtime-cache'),'keep');const a=new LoginMemory(dir);a.record('123456');a.forget();assert.equal(new LoginMemory(dir).account,'');assert.equal(fs.readFileSync(path.join(dir,'runtime-cache'),'utf8'),'keep')}));
test('invalid and corrupt account metadata never restores another account',()=>fixture(dir=>{for(const account of ['',123456,'../123456','abc','123'])assert.equal(validAccount(account),false);fs.writeFileSync(path.join(dir,'login-memory.json'),'{bad');assert.equal(new LoginMemory(dir).account,'');fs.writeFileSync(path.join(dir,'login-memory.json'),JSON.stringify({remember:true,account:'not-a-qq'}));assert.equal(new LoginMemory(dir).account,'')}));
test('first launch of new version reuses the only account with local device credentials',()=>fixture(dir=>{const cfg=path.join(dir,'qq-profile','napcat-work','config');fs.mkdirSync(cfg,{recursive:true});assert.equal(new LoginMemory(dir,cfg).account,'');
 for(const n of ['napcat.json','onebot11.json','napcat_10000002.json','napcat_protocol_10000002.json','onebot11_10000002.json'])fs.writeFileSync(path.join(cfg,n),'{}');
 const seeded=new LoginMemory(dir,cfg);assert.equal(seeded.account,'10000002');assert.equal(seeded.view.seeded,true);assert.equal(fs.existsSync(path.join(dir,'login-memory.json')),false);
 seeded.record('10000002');assert.equal(new LoginMemory(dir,cfg).account,'10000002');assert.equal(new LoginMemory(dir,cfg).view.seeded,false)}));
test('ambiguous local accounts never guess, and saved preference always wins',()=>fixture(dir=>{const cfg=path.join(dir,'cfg');fs.mkdirSync(cfg,{recursive:true});
 for(const n of ['napcat_111111.json','napcat_222222.json','napcat_badname.json','napcat_12.json'])fs.writeFileSync(path.join(cfg,n),'{}');
 assert.equal(new LoginMemory(dir,cfg).account,'');const saved=new LoginMemory(dir,cfg);saved.record('222222');assert.equal(new LoginMemory(dir,cfg).account,'222222')}));
test('runtime auto-login targets only explicit remembered account, never passwords',()=>{const c=managedConfigs(1,2,'w','s','123456');assert.equal(c.web.autoLoginAccount,'123456');assert.equal(managedConfigs(1,2,'w','s','invalid').web.autoLoginAccount,'');assert.ok(!JSON.stringify(c).includes('password'));assert.equal(c.onebot.network.websocketServers[0].host,'127.0.0.1')});
